stages:
  - build
  - test
  - release
  - cleanup

include:
  - component: "$CI_SERVER_FQDN/ees/rdp/generic-components/rdp-cicd-components/kaniko@main"
    inputs:
      stage-test-image: release


variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# =============================================================================
# Build the installable package
# =============================================================================

.build-package:
  stage: release
  tags:
    - docker
    - x86_64
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.10
  variables:
    VERSION_FORMAT: "{base}.post{distance}.dev+{commit}"
  script:
    - pip install -r requirements-dev.txt
    # Guess the version number (no versioneer needed)
    - DST_VERSION=$(dunamai from git --format "${VERSION_FORMAT}")
    - echo Write destination version $DST_VERSION
    - poetry version "$DST_VERSION"
    # Build the project
    - poetry build
    # Push the package
    - poetry config repositories.gitlab-intern ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab-intern gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry publish --repository gitlab-intern

build-package-main:
  extends: .build-package
  variables:
    VERSION_FORMAT: "{base}.post{distance}+{commit}"
  only:
    - main
    - master

build-package-release:
  extends: .build-package
  variables:
    VERSION_FORMAT: "{base}"
  only:
    - tags

build-package-development:
  extends: .build-package
  variables:
    VERSION_FORMAT: "{base}.post{distance}.dev+{commit}"
  only:
    - development
    - 4-create-an-installable-python-package
