stages:
  - build
  - test
  - release
  - cleanup

include:
  - component: "$CI_SERVER_FQDN/ees/rdp/generic-components/rdp-cicd-components/kaniko@main"
    inputs:
      stage-test-image: release


variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# =============================================================================
# Execute the unit tests
# =============================================================================

test-unit-pg14:
  extends: .test-unit
  variables:
    TS_VERSION: "2.18.0-pg14"
    RDP_EXPECTED_POSTGRES_VERSION: "14\\..*"

test-unit-pg16:
  extends: .test-unit
  variables:
    TS_VERSION: "2.18.0-pg16"
    RDP_EXPECTED_POSTGRES_VERSION: "16\\..*"

test-unit-pg17:
  extends: .test-unit
  variables:
    TS_VERSION: "2.18.0-pg17"
    RDP_EXPECTED_POSTGRES_VERSION: "17\\..*"

.test-unit:
  stage: test
  variables:
    TS_VERSION: "2.18.0-pg14"
    PYTHON_VERSION: "3.11"
    RDP_POSTGRES_HOST: "postgres"
    POSTGRES_DB: "rdp_db"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    POSTGRES_USER: "${POSTGRES_USER}"
    RDP_POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/rdp_db"
    RDP_POSTGRES_URL_INIT: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres"
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/timescale/timescaledb:${TS_VERSION}
      alias: postgres
  tags:
    - docker
    - x86_64
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/python:${PYTHON_VERSION}
  script:
    - pip install -r requirements-dev.txt
    - poetry install --all-extras --with dev
    - PYTHONPATH="${PYTHONPATH}:.:tests" poetry run pytest --junitxml=report.xml --log-cli-level=DEBUG tests
  artifacts: # Collect test results
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml


# =============================================================================
# Build the installable package
# =============================================================================

.build-package:
  stage: release
  tags:
    - docker
    - x86_64
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.10
  variables:
    VERSION_FORMAT: "{base}.post{distance}.dev+{commit}"
  script:
    - pip install -r requirements-dev.txt
    # Guess the version number (no versioneer needed)
    - DST_VERSION=$(dunamai from git --format "${VERSION_FORMAT}")
    - echo Write destination version $DST_VERSION
    - poetry version "$DST_VERSION"
    # Build the project
    - poetry build
    # Push the package
    - poetry config repositories.gitlab-intern ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab-intern gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry publish --repository gitlab-intern

build-package-main:
  extends: .build-package
  variables:
    VERSION_FORMAT: "{base}.post{distance}+{commit}"
  only:
    - main
    - master

build-package-release:
  extends: .build-package
  variables:
    VERSION_FORMAT: "{base}"
  only:
    - tags

build-package-development:
  extends: .build-package
  variables:
    VERSION_FORMAT: "{base}.post{distance}.dev+{commit}"
  only:
    - development
    - 4-create-an-installable-python-package
