stages:
  - build
  - test
  - release
  - cleanup

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Creates the docker images
build-images:
  stage: build
  tags:
    - baremetal
    - shell
  script:
    - docker build --pull --file docker/Dockerfile -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  tags:
    - baremetal
    - shell
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main

# Removes any local docker image to avoid littering the build host
cleanup-images:
  stage: cleanup
  tags:
    - baremetal
    - shell
  script:
    - docker images --filter=reference="${CI_REGISTRY_IMAGE}"
    - docker rmi -f $(docker images --filter=reference="${CI_REGISTRY_IMAGE}" -q)
    - docker images
  when: always