# Configuration for the documentation hosted via Github pages 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: RDP Database
description: Hosts the scheme as well as the migration scripts that set up the long-term storage based on Timescale DB.
show_downloads: true
